import type { Metadata } from "next";
import { Outfit as fontSans } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

const font = fontSans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Blockchain Crowdfunding",
  description: "Generated by Batch B4 for Mini Project AY 2023-24",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
